### ISSUE TITLE
error occured: ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by bianbiandashen** [liangwei-artefact/langchain-supabase-website-chatbot-demo#1]
![image](https://github.com/liangwei-artefact/langchain-supabase-website-chatbot-demo/assets/16240681/a88c540c-3f8e-4c16-883e-61ccd4e04a2a)

**Comment by liangwei-artefact** [comment]
你可以试试直接写个，我把代码直接改成，我自己使用的了
